ALTER TABLE client_requests ADD COLUMN IF NOT EXISTS baggage VARCHAR(20) DEFAULT '';
ALTER TABLE client_requests ADD COLUMN IF NOT EXISTS tariff VARCHAR(40) DEFAULT '';
ALTER TABLE client_requests ADD COLUMN IF NOT EXISTS child_seat BOOLEAN DEFAULT FALSE;
ALTER TABLE client_requests ADD COLUMN IF NOT EXISTS booster BOOLEAN DEFAULT FALSE;
ALTER TABLE client_requests ADD COLUMN IF NOT EXISTS animals BOOLEAN DEFAULT FALSE;
