INSERT INTO t_p67171637_yug_transfer_prize_l.knowledge_base (title, category, content)
SELECT v.t, v.c, v.u FROM (VALUES
('Группа 2093706331','Группы','https://t.me/c/2093706331/1'),
('ТРАНСФЕР по МИРУ','Группы','https://t.me/c/2104320856/1'),
('Группа 2229533760','Группы','https://t.me/c/2229533760/1'),
('🏔KAVKAZ-TRANSFER 🧭','Группы','https://t.me/c/2384819110/1'),
('@cernozem046','Группы','https://t.me/cernozem046'),
('VIP TRAVEL - UG','Группы','https://t.me/dhgsghhggb345436'),
('46 Трансфер','Группы','https://t.me/ksktransfer'),
('🔥МИНИВЕНЫ 7+🔥ПО МИРУ','Группы','https://t.me/miniven321'),
('Prime taxi не подключена к боту','Группы','https://t.me/qY2QVlq_8oY5ZmZi'),
('KAVKAZ-TRANSFER','Группы','https://t.me/subcaucasbot?start=sub81313'),
('ТАКСИ 🚕 ДНР - ЛНР Межгород РФ','Группы','https://t.me/taxi_DONETSK_LNR'),
('Трансфер РФ Новые Территории 🇷🇺','Группы','https://t.me/taxi_RF_new'),
('⚡️ТРАНСФЕР-ИМПЕРИЯ⚡️не работает…','Группы','https://t.me/taxi_mezgorod_imperya'),
('Такси Оптима (Вся Россия)','Группы','https://t.me/taxioptima072021'),
('МОË-ТАКСИ МЕЖГОРОД','Группы','https://t.me/taxsimuy'),
('АвтоЛайн 3000 р/мес по вступлен…','Группы','https://t.me/toplinevip'),
('«СОЮЗ ПАРТНЕРОВ» 400 р','Группы','https://t.me/transfer761'),
('Трансферы Ростовская область не…','Группы','https://t.me/transferRostOBL'),
('Такси Межгород 24/7','Группы','https://t.me/transfer_taxi_poezdki/6194'),
('GOOD TAXI - 250 р/мес регистрац…','Группы','https://t.me/uptaxiVRN_job'),
('Вежливые Люди ( 500 р единоразо…','Группы','https://t.me/vejlivie_svoi'),
('TAXI - T-34','Группы','https://t.me/wwwtaxit34'),
('ЦЕНТРАЛ   через бот @payment_ce…','Группы','https://t.me/yti_pyti001'),
('Transfer 24','Группы','https://t.me/zahodivtransfer'),
('777','Группы','https://t.me/supp777_bot'),
('BLACK TAXI','Группы','https://t.me/transfertaxi23'),
('CABWAY-Transfer (вход 500 р)','Группы','https://t.me/JV2zVoP99JQwOGFi'),
('DenAlenBus Ссылка на добавление…','Группы','https://t.me/denalenbus_bot'),
('DONBASS INTERCITTY (Бот для доб…','Группы','https://t.me/donbass_group_bot'),
('Golden Horse Трансфер','Группы','https://t.me/Golden_Horse_online'),
('GOLDEN V.I.P - 5000р/мес','Группы','https://t.me/paygoldenvipbot'),
('Mika - Travel','Группы','https://t.me/Mika555_555_555'),
('MOSKVA LNR DNR TRANSFER','Группы','https://t.me/MoskvaSB84'),
('MOSKVA LNR DNR TRANSFER 300 р/м…','Группы','https://t.me/paylnrbot'),
('Neuro Go','Группы','https://t.me/NeurogoDriver'),
('NoTaxi','Группы','https://t.me/Notaxings'),
('OMSKPREMIUM555','Группы','https://t.me/OMSKPREMIUMqw'),
('PREMIUM TAXI🚕','Группы','https://t.me/premiumtaxi31'),
('REGION TRANSFER','Группы','https://t.me/RegionTransferrr'),
('RND Travel VIBES','Группы','https://t.me/RND_TRAVELVIBES161'),
('Russian Taxi','Группы','https://t.me/RussianTaxiRF'),
('TAXI FORTUNA','Группы','https://t.me/Rostov_na_Donu_Fortuna'),
('Trans Service RUS 🇷🇺','Группы','https://t.me/trans_service_rus'),
('TRANSFER AVTO','Группы','https://t.me/TRANSIFER_AVTO'),
('АВАНГАРД','Группы','https://t.me/AvangardTransFer1'),
('Армата Межгород','Группы','https://t.me/armatavip36'),
('Вип МОЁ','Группы','https://t.me/taxsimoevip'),
('Галопом по Европе и РФ','Группы','https://t.me/GalopomRF'),
('Город в Город Межгород','Группы','https://t.me/izgorodavgorod'),
('ГОРЯЧИЕ ЗАКАЗЫ','Группы','https://t.me/ugtransferrr'),
('Драйвер САРАТОВ КОМФОРТ','Группы','https://t.me/Driver_SARATOV'),
('Дюма- междугородние заказы','Группы','https://t.me/duma064'),
('Заказы Такси #82 КРЫМ','Группы','https://t.me/KPbIM_8_2'),
('Лайт Такси Межгород','Группы','https://t.me/mezgorodlight'),
('Межгород такси НАРО-ФОМИНСК - М…','Группы','https://t.me/taxsiLosi'),
('Междугороднее Такси','Группы','https://t.me/taxi_meg'),
('Метеора','Группы','https://t.me/meteoraRF'),
('Наше такси - Межгород','Группы','https://t.me/our310'),
('Новороссия Трансфер','Группы','https://t.me/NovorossiyaTransferRF'),
('Новороссия Трансфер РФ🚕🚕🚕 ( htt…','Группы','https://t.me/paynovorossiabot'),
('Первый Трансфер Межгород','Группы','https://t.me/one_transfer1'),
('Проект Гагарин!!!','Группы','https://t.me/gagariniiii'),
('Профсоюз Партнёров!','Группы','https://t.me/komandaii'),
('Регион 69','Группы','https://t.me/reg69transfer'),
('Россия Трансфер (вход 500 р)','Группы','https://t.me/RussiaTransfer1'),
('Рулю 24/7','Группы','https://t.me/RulyRF'),
('Срочные Заказы Такси по Крыму','Группы','https://t.me/SRO4NO82'),
('Такси - Межгород. Тут ТОЛЬКО за…','Группы','https://t.me/poputka_taxi_obratka'),
('Такси | Крым','Группы','https://t.me/taxicrimea'),
('Такси | КРЫМ и КУБАНЬ','Группы','https://t.me/taxi_krim_kuban'),
('Такси Межгород 24/7','Группы','https://t.me/transfer_taxi_poezdki'),
('Такси Межгород _777_ Белгород','Группы','https://t.me/Arch19922'),
('Такси Межгород РФ','Группы','https://t.me/servisetaxi'),
('Такси 🚖Бумер🚕 междугородние пое…','Группы','https://t.me/BumerTopTaxiRuss'),
('Трансфер | Good Taxi','Группы','https://t.me/good_taxi_job'),
('Трансфер Колесо Плюс','Группы','https://t.me/transfer_koleso_plus'),
('Трансфер Корона','Группы','https://t.me/TaxiKoronaTransfer'),
('Трансфер УРАЛ - СИБИРЬ - БАШКИР…','Группы','https://t.me/welcome_to_transfer'),
('УРАЛ МЕЖГОРОД','Группы','https://t.me/taximiass774driverbot'),
('Южный','Группы','https://t.me/yujnitransfer'),
('…ГРАНИЦА…','Группы','https://t.me/CONCORDE_TAXI_ZV'),
('Ⓜ️" 𝑴𝑶𝑺.𝑻𝑨𝑿𝒊 - 𝑺𝑽𝑶𝒊 𝑨𝑵𝑮𝑬𝑳 "','Группы','https://t.me/mostaxi_svoy_angel'),
('𝐓𝐚𝐤𝐬𝐢𝐏𝐨𝐑𝐨𝐬𝐬𝐢𝐢','Группы','https://t.me/TaksiPoRossii_777'),
('🇷🇺‼️ТАКСИ УРАЛ ‼️🇷🇺','Группы','https://t.me/vostok9999911'),
('🏔KAVKAZ-TRANSFER 🧭  (Бот для до…','Группы','https://t.me/subcaucasbot'),
('👑KOBRA👑','Группы','https://t.me/KOBRAtransfer'),
('👑ТУДА-СЮДА👑 КРЫМ👑','Группы','https://t.me/TYDAsydaCRIMEA'),
('🔥Топ Лайн🔥 Для вступления необх…','Группы','https://t.me/toplinevipbot'),
('🚖 ЛЕГЕНДА 🚖','Группы','https://t.me/taxi_legenda'),
('🚗Джанкой трансфер экспресс быст…','Группы','https://t.me/De16061983'),
('🚘 Dedline Трансфер по РФ','Группы','https://t.me/transfer23RF'),
('KubanTransGroup VIP НЕ ПОДКЛЮЧЕ…','Группы','https://t.me/+-gyIc2GQkaczYWYy'),
('KRAS VIBE TRAVEL','Группы','https://t.me/+4amQG5Cq1T5hZWI1'),
('Такси Ямщик ( если ссылка не ра…','Группы','https://t.me/+5MSDU16z5LI0ODNi'),
('VIP ONE#K2 ( 3000 мес ) @oplata…','Группы','https://t.me/+5XIFe23XaMI1ZTli'),
('Междугороднее такси СВО и вся Р…','Группы','https://t.me/+70j55jeOtuFjMzIy'),
('Свой Путь','Группы','https://t.me/+AbydC1Gcgdw2ZTk6'),
('88888888','Группы','https://t.me/+8oCymj-aePwxY2Qy'),
('KRAS VIBE TRAVEL','Группы','https://t.me/+2Zkd6aniP9k1Mzk1'),
('Marriott трансфер','Группы','https://t.me/+YMWhHifygGU0MTI6'),
('SKY Трансфер  Медгород','Группы','https://t.me/+oELboq5Zm8Q4ZjJi'),
('VIP Fast Track','Группы','https://t.me/+npX6v2qwotliMTVi'),
('VLG VIBE TRAVEL','Группы','https://t.me/+J6luzUsQNDhhZjY6'),
('Волга Такси','Группы','https://t.me/+Tjj41h6UqK9jNWEy'),
('КОМПАС РОССИИ','Группы','https://t.me/+_ahViLZOhQlkMjNi'),
('Междугороднее такси "Соловей"','Группы','https://t.me/+ZvnL76QwfGIzODli'),
('МежТрансфер - Сити По России','Группы','https://t.me/+co72RH6E-IIwNTIy'),
('Минивэны EV Трансфер','Группы','https://t.me/+rwyFyXo1Bgg5NDQy'),
('Такси Краснодар - МЕЖГОРОД','Группы','https://t.me/+x7-DWq2I2NhmMjky'),
('Трансфер Быстрый путь','Группы','https://t.me/+EezPORfmydsyZTZi'),
('♨️RU TRANSFER♨️','Группы','https://t.me/+w_pW6XDijNdjNTQy'),
('A̺͆R̺͆T̺͆T̺͆A̺͆X̺͆I̺͆ Заказы по…','Группы','https://t.me/+BMmrhZrzDwpmODli'),
('ГК — Сибирь','Группы','https://t.me/+CoaJpTbk2NQ5ZTFi'),
('Orange Group','Группы','https://t.me/+D-kEVup8W2wzNDUy'),
('" MosTaxi - СВОй Ангел "','Группы','https://t.me/+D7LfveRp2ZkxN2Vi'),
('VIP ONE#K2','Группы','https://t.me/+EhTBrl_uteg1NjBi'),
('МИНИВЕН 24/7 LEGION','Группы','https://t.me/+FRbYHU6eWXoyNTIy'),
('ОБЩЕНИЕ +++ (ТРАНСФЕР/ТАКСИ)','Группы','https://t.me/+FzyU02_T980zYzUy'),
('ЕСТ Единая Служба Такси','Группы','https://t.me/+IILMF2nvAv9kYzUy'),
('VeZёT владелец @Vezet161','Группы','https://t.me/+J1IfGRxsb79lMWZi'),
('Заказы по России (⛔️1000р/мес) …','Группы','https://t.me/+LZOiuqzqi0E3NzQy'),
('МежТрансфер - Сити По России','Группы','https://t.me/+MO8uJEG5ycs3NmQy'),
('ComfortRussian','Группы','https://t.me/+NWdIMuCUhKIyZjAy'),
('Минивэны EV Трансфер','Группы','https://t.me/+O7WYTsJ_HPw0M2Qy'),
('ComfortRussianVIP','Группы','https://t.me/+OaOlJKfhAcdlODEy'),
('ГК — Межгород','Группы','https://t.me/+PyQCHg0NyYc0NWRi'),
('Элитка','Группы','https://t.me/+QE-IYSGL_4c1MWY6'),
('ХХХ','Группы','https://t.me/+RHW_Kv1-Od0xMTVi'),
('Zемля🇷🇺 Трансфер РФ','Группы','https://t.me/+S8CR2k37DXU5NmQ6'),
('CARNIVAL TRANSFER писать владел…','Группы','https://t.me/+SA0Hg3AmABVmNTMy'),
('Z - TOUR владелец @hotkuda5','Группы','https://t.me/+Sp6uzXLOE9M3MDhi'),
('🛫🚖Трансфер Юг РФ🚖🛬* (  Такси по…','Группы','https://t.me/+T4OL9MGDex5mZWIy'),
('💎DIAMOND💎TAXI💎 ( @Vo…','Группы','https://t.me/+TBIKY9XdV1IwNzUy'),
('GANGSTER AUTO 350 Р/мес через б…','Группы','https://t.me/+TNacPVM7m_xlNWI6'),
('ГК — Россошь','Группы','https://t.me/+TkJyxcjT7RlhNTNi'),
('СтоДорог СЗФО','Группы','https://t.me/+Tl_8lko8HFY3MDEy'),
('VOLGA.TAXI🌊 (500 р единоразово)','Группы','https://t.me/+UXjikFrK0Ak3MmQ6'),
('LUXURY TRANSFER','Группы','https://t.me/+UriQB-IkYjNiOWUy'),
('Cars-team - 1500 р/мес вход чер…','Группы','https://t.me/+VMeoviIcURM2MjM6'),
('ZineX Междугороднее Такси по РФ','Группы','https://t.me/+Ve4aHM_SShw4MGZi'),
('VIP АЛЬЯНС ( 1000 мес) регистра…','Группы','https://t.me/+VhXX61lEIy1hYWNi'),
('ЛогиМажор','Группы','https://t.me/+VzHtUdYwzr8zNDUy'),
('Трансфер','Группы','https://t.me/+WRa0zIWWh7k4YWRi'),
('ГК — Минивены','Группы','https://t.me/+Wj1_UMRRuAJkNWIy'),
('🚗Джанкой трансфер экспресс быст…','Группы','https://t.me/+XvQ3mO8IyfwzMzdi'),
('ДальнТакси межгород','Группы','https://t.me/+XwHT6sz-FC0zOWUy'),
('Трансфер -Крым, Армянск, Новые …','Группы','https://t.me/+Y0fce5BwHX05NmZi'),
('Vip Rides nap','Группы','https://t.me/+YUdLp3H7XWU4YzJi'),
('На Край Света🪂⏱️✈️⛵️ (440р) ( п…','Группы','https://t.me/+YXe19WzEeqE2YTdi'),
('ГК — Свободные Заказы','Группы','https://t.me/+ZOJiPqqIZsM4OWMy'),
('TM_SVOy_PUT_VIP (3500 на первое…','Группы','https://t.me/+ZwRUmAYG9Js1NzY6'),
('G - Transfer','Группы','https://t.me/+_BQ2WIVVRWlkMDIy'),
('⚜️Vip Individual⚜️(1500)','Группы','https://t.me/+_O0heE4JBL1iNzEy'),
('ТАКСИ ПО РФ И СВО','Группы','https://t.me/+_TfgFMBcDrVkZWUy'),
('ТК - TravelSmart ( 1000 р един )','Группы','https://t.me/+aARyLvo5eARhM2Uy'),
('V.I.P “VeZemRF”  1000 р/мес','Группы','https://t.me/+aLPhv9YxO6BlMzVi'),
('VIP трансфер Межгород','Группы','https://t.me/+aSFLD7-U36M2NDdi'),
('🚖ТАКСИ️-ВСЯ-РОССИЯ🇷🇺 не подключ…','Группы','https://t.me/+bM2L4g4EyM43Y2Ji'),
('CoMPaSs- TRansFeR','Группы','https://t.me/+biXjXkqWenNmOTg6'),
('СУРГУТ⚛️TRANSFER ( заказы по Тю…','Группы','https://t.me/+bpwQCWxRdtc1NDFi'),
('ТАКСИ Краснодар - МЕЖГОРОД писа…','Группы','https://t.me/+d-JSD-LeNz5lZjUy'),
('МИНИВЭНЫ | КРЫМ | РФ','Группы','https://t.me/+e7LTX--MAQw5NDEy'),
('JOKER ( 500)','Группы','https://t.me/+fDTq2MROqHpiNzU6'),
('RUS TAXI регистрация через бот …','Группы','https://t.me/+gX7GTwdLXig0NzRi'),
('ТРАНСФЕР РФ-2 писать владельцу …','Группы','https://t.me/+ghtXzmfzCZ9lZDky'),
('БУС - ТРАНСФЕР','Группы','https://t.me/+ho3OJ_8WeRk4ZjUy'),
('OMEGATRANSFER по вступлению пис…','Группы','https://t.me/+ijzJpbyhKs5kYzM6'),
('Такси Межгород Стрела','Группы','https://t.me/+iyk_WOcIAZs1ZTAy'),
('Zемля Трансфер РФ','Группы','https://t.me/+kyVotQeU6vdjYmZi'),
('ГК — Сибирь','Группы','https://t.me/+le75hk_xMGk1NWMy'),
('Ты мне - я тебе группа закрытая…','Группы','https://t.me/+m3EzKh_cCH42N2Qy'),
('VIP 999','Группы','https://t.me/+m3phMCsLbWRkNjIy'),
('Стимул Москва и Центр','Группы','https://t.me/+morvINdmbtw3NDk6'),
('Vip Вне_Закона ( 2500 мес )','Группы','https://t.me/+n-9RUfWTpRc5ZTEy'),
('ИМПЕРИЯ VIP','Группы','https://t.me/+nJaw17xCWWo0MTEy'),
('ГК — Северо-Запад','Группы','https://t.me/+ncSuxvaeJYQ1MGFi'),
('Donbass Intercity + РФ регистра…','Группы','https://t.me/+oMNI2r0lQLU1MjQy'),
('Sky transfer','Группы','https://t.me/+q3eNeSP2ogM4YzYy'),
('Трансфер Поволжье (РФ)','Группы','https://t.me/+qdvNtGQAXUE5ZDAy'),
('PRESTIGE','Группы','https://t.me/+r0SCxl9dAj5kY2Zi'),
('Минивэны,Ларгусы','Группы','https://t.me/+r4Jowhcw2-VmMmQy'),
('ГК — Белгород','Группы','https://t.me/+r5I-6EwjIaViNjAy'),
('SKY VIP ( 1500)','Группы','https://t.me/+rK9oq5mvq2E5NDA6'),
('ЧЕСТНЫЙ ТРАНСФЕР (  ТРАНСФЕР МО…','Группы','https://t.me/+rnYCNkmwwYNjNzFi'),
('ПЕНЗА ТАКСИ МЕЖГОРОД - РФ','Группы','https://t.me/+t1oRaBvhmBQ5OWRi'),
('ГК — Новые Территории','Группы','https://t.me/+tbiGcEvTvwY0YWUy'),
('Wings Transfer 500 р/единор','Группы','https://t.me/+uXAiC0y7M7ljN2Yy'),
('RideSnap Travel (300 р един )','Группы','https://t.me/+uXlTcsNQvehkMDQ6'),
('ПОБЕДА ТРАНСФЕР','Группы','https://t.me/+wTaQzGetOgIzMmEy'),
('‼️НАШ МЕЖГОРОД‼️ НЕ ПОДКЛЮЧЕНА …','Группы','https://t.me/+x2D2uQJPuMM0OTRi'),
('ComfortRussianVIP','Группы','https://t.me/+y54JDLEiSNI0MjZi'),
('K2 VIP ( 1500 мес )','Группы','https://t.me/+yeceitfpFixkYTI6'),
('ТРАНСФЕР-БЕЗ-ГРАНИЦ','Группы','https://t.me/+yijkhW0NC2A2M2Yy'),
('VIP №1 (2000) писать владельцу …','Группы','https://t.me/+ypOe1RUWDjAzOTYy'),
('СтоДорог ЮГ','Группы','https://t.me/+zK1UGpZV3kUzMTUy'),
('VIP МОЁ-ТАКСИ ( 2000 мес )','Группы','https://t.me/+zrRh6pCChLM3MGVi'),
('"ОРЛОВСКИЙ" межгород','Группы','https://t.me/+kROmWx7jQtpjNjQ6'),
('06.2026 набор закрывается !','Группы','https://t.me/+Fr9CV-U2Y400MzQy'),
('ARISTOCRAT','Группы','https://t.me/+yZCxPex2HzBkOTJi'),
('Family Travel Трансфер 24/7 ( п…','Группы','https://t.me/+8g81TmLV23NlODQy'),
('K2 группа 🇷🇺','Группы','https://t.me/+EpAXjNdUOuM5NDli'),
('Like Taxi (вход 500 р)','Группы','https://t.me/+-lZfYn18IAo3MTIy'),
('MosTaxi - ЖЕНСКАЯ ЛИГА','Группы','https://t.me/+0ZuDwb_cIXA2YjEy'),
('TAXI - KORDON Transfer 🇷🇺🌎','Группы','https://t.me/+0pIcwzKejHkyZDIy'),
('TRAVEL - YUG мы везде оглянись 🔥','Группы','https://t.me/+osKHvwDnD8QzZDAy'),
('UFA VIBE TRAVEL','Группы','https://t.me/+Om8TC9VapqwyMDA6'),
('VLG VIBE TRAVEL','Группы','https://t.me/+BJ601nI6I6g1MDcy'),
('VLG VIBE TRAVEL','Группы','https://t.me/+Lnlv-w--l5YzOGU9'),
('YouVTaxi Междугородние поездки','Группы','https://t.me/+vvG15Ds20tllZmY6'),
('ААЕ - ТРАНСФЕР','Группы','https://t.me/+zFNfdtej2w03NjBi'),
('Без Шашечек РФ','Группы','https://t.me/+UxSrxdFQu15mYmMy'),
('БУНТ трансфер','Группы','https://t.me/+dz4FZDRbcdI2ZGU6'),
('Везет GO!','Группы','https://t.me/+MgKleSnweFk3ZjNi'),
('Вип G-transfer','Группы','https://t.me/+GAQEEARoLrVlY2Yy'),
('Дальний восток Сибирь','Группы','https://t.me/+bxqLxS638OdkMDg6'),
('Заказы со всех групп','Группы','https://t.me/+DZzKRUjr0clhOWIy'),
('Заявки такси','Группы','https://t.me/+OQLFEWQjIFs1Y2Zi'),
('КОСМОС','Группы','https://t.me/+o74eYk9WF6dhMTUy'),
('Круиз Такси','Группы','https://t.me/+L5rgXbcMYmIyZWZi'),
('Крымский мост и Краснодарский к…','Группы','https://t.me/+L7ngkyfHKZNjYjAy'),
('Кубань','Группы','https://t.me/+In1tWM4CW6QyYzYy'),
('МежГорТранс','Группы','https://t.me/+4ezShyoAqiplNTVi'),
('МЕЖДУНАРОДНИКИ','Группы','https://t.me/+KAF8xApy6tZkNmQy'),
('МИНИВЕНЫ Межгород НАРО - ФОМИНС…','Группы','https://t.me/+mB1FWLUcsCQ0ZTIy'),
('МИР VIBE TRAVEL','Группы','https://t.me/+wb3LQ0YBrRs0Y2Ri'),
('МОТОР по РФ','Группы','https://t.me/+0R5phIVf_3M0YjIy'),
('НОВАЯ РОССИЯ','Группы','https://t.me/+QqHRH6v52qs4ZDJi'),
('ОРЛОВСКИЙ MOSCOW CITY','Группы','https://t.me/+OcoPQlTAF0oxYjYy'),
('ПтС (ПРОДАМ только СВОИМ)','Группы','https://t.me/+dag2En1lz7llNGUy'),
('РОССИЯ И СНГ','Группы','https://t.me/+Q549w9JJYIRiY2Vi'),
('РУБИКОН ТАКСИ МЕЖГОРОД','Группы','https://t.me/+RP3lY_25y7IyZTFi'),
('Русский Трансфер','Группы','https://t.me/+ZaD_BUunsHk2ZTVi'),
('СВОё Такси','Группы','https://t.me/+JS9NYfVsuF45ZTNi'),
('Сибирь Транс','Группы','https://t.me/+pl_gBefqsuMxZTAy'),
('Такси Волна','Группы','https://t.me/+ykEXCArv4pYxMTAy'),
('Такси Марсель','Группы','https://t.me/+Ybka0x7x0OoxYTdi'),
('Такси межгород АПП Изварино','Группы','https://t.me/+e6okeL-UU6A5YjIy'),
('Такси Мобил Межгород','Группы','https://t.me/+lpong4D_2MFlNjQy'),
('Трансфер «СИМАРТ»','Группы','https://t.me/+dHPHqZRtjn0xMmMy'),
('Трансфер Москва и ЦФО','Группы','https://t.me/+cAf7b81jHawwYjI6'),
('Трансфер РФ','Группы','https://t.me/+DIqLBzEeWJlkNTIy'),
('Трансфер СЕВЕР','Группы','https://t.me/+14FdnSqq-ws1MGFi'),
('Трансфер-Групп','Группы','https://t.me/+jebjnAoczpMxMmUy'),
('Ⓜ️" 𝑴𝑶𝑺.𝑻𝑨𝑿𝒊 - МИНИВЕНЫ "','Группы','https://t.me/+4fI51yoj7sE4ODYy'),
('⚜️ Такси ELITE TRANSFERS ⚜️','Группы','https://t.me/+dKON9P6v_hQ2YmJi'),
('𝒁𝒊𝒏𝒆𝒙 𝑴𝒆𝒛𝒉𝒈𝒐𝒓𝒐𝒅𝒏𝒆𝒆 𝑻𝒂𝒌𝒔𝒊 𝒑𝒐 𝑹𝑭','Группы','https://t.me/+z22I4TSwpCk2MTUy'),
('🆅🅸🅿️ - Go Transfer 🚘','Группы','https://t.me/+XdVsAvKAysthNjcy'),
('🇷🇺 56 T. TRANSFER 🇷🇺','Группы','https://t.me/+uTHlQJr4qm04Mjli'),
('🔥Топ Лайн🔥 ( общая )','Группы','https://t.me/+O7JKyZ49rNw5ZmNi'),
('Мой Трансфер','Группы','https://t.me/moy_transfer'),
('Доставка Грузов По России','Группы','https://t.me/gruz_bustro'),
('Такси Лидер Междугороднее','Группы','https://t.me/mezhgorodlidertop'),
('БиБиКарRF','Группы','https://t.me/BiBicarRF'),
('🚕Муром Едет🚕','Группы','https://t.me/taxivmurome'),
('Крымское Такси','Группы','https://t.me/TAXI_82'),
('🤙 𝑻𝑨𝑲𝑺𝑰 𝑺𝑽-𝑭𝑶𝑹𝑻𝑼𝑵𝑨 🤙','Группы','https://t.me/FortunaSV'),
('Такси / Трансфер Крым + Материк','Группы','https://t.me/Tavridataxi'),
('LONG_DISTANCE TRAVEL','Группы','https://t.me/LongDistanse_Transfersss'),
('🚕RussianTaxi🚕Город☎️','Группы','https://t.me/gorodRussianTaxi'),
('KORDON Transfer','Группы','https://t.me/KORDON_TRANSFER_RU'),
('СРОЧНЫЕ 🔥 | КРЫМ и КУБАНЬ','Группы','https://t.me/taxi_krim_kuban_now'),
('Эльбрус Трансфер Чегет Терскол …','Группы','https://t.me/edemnaelbrus'),
('Orange Group','Группы','https://t.me/Orange_Groupps'),
('Заказы Такси ДНР ЛНР РФ','Группы','https://t.me/zakaznikDNR'),
('PRIME TAXI™','Группы','https://t.me/PrimeTaxiTransfer'),
('LEGION | МИНИВЭН 24/7 🇷🇺','Группы','https://t.me/minivan_legion'),
('Южный трансфер Russia 🇷🇺','Группы','https://t.me/Q7pi6FLZjKtmODdi'),
('Колесо Плюс Трансфер','Группы','https://t.me/kolesoplustransfer37'),
('ПЕНЗА ТРАНСФЕР ПО РОССИИ TRUST …','Группы','https://t.me/penzatrusttransfer'),
('Самарское Такси. Самара 🚖','Группы','https://t.me/transfersRF'),
('💲 Такси ТрансфеР','Группы','https://t.me/HGJd3I9QglEzZDA6'),
('Первые ВИП','Группы','https://t.me/perviegorod'),
('🚕🚕🚕Куплю заказ Ростовская Облас…','Группы','https://t.me/transferRostOBLkuply'),
('🚘ТАКСИ ДЛЯ СВОИХ 🚖','Группы','https://t.me/taxielitaRF'),
('Междугороднее такси Таганрог, Р…','Группы','https://t.me/tagrostaxi'),
('Ангелы хранители межгород 😇','Группы','https://t.me/tb1vEnDXjSM5Y2I6'),
('Межгород Уфа aTaxi','Группы','https://t.me/mezhgorodataxi'),
('🤝 Ты Мне Я Тебе 🤝','Группы','https://t.me/Tbl_Mne_Ya_Tebe'),
('СВ-ЗАКАЗЫ','Группы','https://t.me/svzakaz'),
('МЕЖДУГОРОДНЕЕ ТАКСИ РОССИИ !!! …','Группы','https://t.me/mejgortaxi'),
('междугороднее такси Таганрог, Р…','Группы','https://t.me/ru_taxi_rus'),
('KAMA TRANSFER | Водители • Дисп…','Группы','https://t.me/kamatransfer'),
('CRIMEA AIRLINES','Группы','https://t.me/crimea_airliness'),
('🏂 Межгород НСК🌍🏕','Группы','https://t.me/borobavka'),
('ТAXI RF','Группы','https://t.me/Takcu_RF'),
('𝐓𝐀𝐗𝐈_𝐒𝐈𝐓𝐈_𝐋𝐀𝐈𝐍','Группы','https://t.me/SITI_LAIN'),
('💠СТК Север-Запад💠','Группы','https://t.me/ctk_sever_zapad'),
('PRIME Transfer','Группы','https://t.me/dark_transferss'),
('АвтоЛайн','Группы','https://t.me/auvtoline'),
('МойТрансферРФ','Группы','https://t.me/MoyTransfer_RF'),
('Такси межгород по России.','Группы','https://t.me/mezhgorod_taxi_russ_minivan')
) AS v(t, c, u)
WHERE NOT EXISTS (SELECT 1 FROM t_p67171637_yug_transfer_prize_l.knowledge_base k WHERE k.category='Группы' AND split_part(k.content, E'\n', 1) = v.u);