INSERT INTO t_p67171637_yug_transfer_prize_l.knowledge_base (title, category, content) VALUES
('Юг Трансфер Вся Россия','Группы','https://t.me/UG_DRIVER'),
('@VIP_TAXI_VIKARS','Группы','https://t.me/VipTAXIVIKARS
👉 Вход в группу через бот: @verif_driver_bot'),
('ЦЕНТРАЛ 🎲','Группы','https://t.me/+GuzlLq0cz_QzYjky
👉 Вход в группу через бот: @verif_driver_bot'),
('Федеральная Система Бронирования','Группы','https://t.me/fsb_service_taxi
👉 Вход в группу через бот: @verif_driver_bot'),
('ПЕРВЫЙ ТРАНСФЕР МЕЖГОРОД','Группы','https://t.me/+RaH-q9uGMyQwNTc6
👉 Вход в группу через бот: @verif_driver_bot'),
('Москва Санкт-Петербург','Группы','https://t.me/+anNqjTARSgw4NzJi
👉 Вход в группу через бот: @verif_driver_bot'),
('Первый Минивены','Группы','https://t.me/+RqWjP7boTis4ZWZi
👉 Вход в группу через бот: @verif_driver_bot'),
('ПЕРВЫЙ СЕВЕРНЫЙ.','Группы','https://t.me/+JRmhZyP5VxxmM2My
👉 Вход в группу через бот: @verif_driver_bot'),
('Юг аэропорты Южный федеральный …','Группы','https://t.me/+IE4uozaManhjNjg6
👉 Вход в группу через бот: @verif_driver_bot'),
('Zelenoglazoe Taxi 🚖 Межгород 🇷🇺…','Группы','https://t.me/+4hPlddENC7owMDgy'),
('CABWAY Город Луганск , Донецк','Группы','https://t.me/+5gvVa4N7_jtjNTcy'),
('/// VIP 999','Группы','https://t.me/+2TkGm-yhBms3ZGQy'),
('RUSTAXI','Группы','https://t.me/+XGHMgrRqENkyZjIy'),
('СВОЙ Трансфер Заказы','Группы','https://t.me/+7DK8VFKWRy9kZDEy'),
('Такси Оптима (Вся Россия)','Группы','https://t.me/+P1rv_DBT4ls5NjIy'),
('Трансфер -Крым, Армянск, Новые …','Группы','https://t.me/+ZGdGvQSlBmRjMWNi'),
('ТРАНСФЕР-ИМПЕРИЯ','Группы','https://t.me/+Q5XdQpBTqaA1MzUy'),
('🎖TAXI PATRIOT🎖','Группы','https://t.me/+ekcn5z0QHSUwYTYy'),
('Transfer Поволжье / Урал','Группы','https://t.me/+26mmiZRTDG80YzQy'),
('ORENTRANSFER ( заказы по Поволж…','Группы','https://t.me/+3RNBh-w9afU2ZDZi'),
('Стимул РФ(вся Россия)','Группы','https://t.me/+3YHQNObtvis4OGYy'),
('VLG TRAVEL VTV134','Группы','https://t.me/+3hsJfWcTKVI2ZWRi'),
('⚜СУРГУТ⚛TRANSFER💠✈️🚂🚘','Группы','https://t.me/+3p0r4Wo1LPs1Mzcy'),
('ТРАНСФЕР СИБИРЬ НЕ ПОДКЛЮЧЕНА','Группы','https://t.me/+4U1pSCsrHhZmNmVi'),
('Юг-Сити-Трансфер(межгород.)','Группы','https://t.me/+735tGEkB3wIwOGEy'),
('ГК — Крым','Группы','https://t.me/+7V8b7PQ9oUI0ODZi'),
('СтоДорог МЕЖГОРОД','Группы','https://t.me/+8Iey4GPk4v01NGRi'),
('ТТ: ТраекТория  2000 р/мес','Группы','https://t.me/+9ZXJo74FsNU5MzJi'),
('ГК — Дальний Восток','Группы','https://t.me/+AW1y25dQNQU2ZTNi'),
('ЛЕНИНГРАД"СТИМУЛ"','Группы','https://t.me/+AWFELBjjFexlNmMy'),
('VIP 58 Пенза','Группы','https://t.me/+AcMJX1Hp55FlNGI6'),
('"VeZem" такси межгород','Группы','https://t.me/+HxKL75cKEpRiZmRi'),
('"МЕЖГОРОД" парк','Группы','https://t.me/+O9OWrAWWx4ZmZDUy'),
('Black Santa','Группы','https://t.me/+M5SFLcIx0FdkYTFi'),
('Ferrari-Russian','Группы','https://t.me/+rNAw2iZeTCxlN2Ri'),
('GANGSTER AUTO','Группы','https://t.me/+Ae3farpjdrhlNzM6'),
('NAO Drivers','Группы','https://t.me/+0Od-_OFWPChiNjMy'),
('PRIME WAY','Группы','https://t.me/+3tM1g9iVGnUwZTNi'),
('Transfer Поволжье / Урал','Группы','https://t.me/+8NWVkHA2SP84NDhi'),
('VIP ONE#K2','Группы','https://t.me/+7zcd7vO10v00ODdi'),
('VIP RideSnap','Группы','https://t.me/+ha1nn0GwKck4MDQy'),
('XXX','Группы','https://t.me/+l_XNJS1mimthNmJi'),
('Zемля🇷🇺 Трансфер РФ🇷🇺','Группы','https://t.me/+g9nEhQiJJycwYTIy'),
('ВИП -  ААЕ - ТРАНСФЕР','Группы','https://t.me/+-m6Z9ZeXx6BiYmVi'),
('ЕСТ Единая Служба Такси','Группы','https://t.me/+_KYeKwoFqg5jMDRi'),
('Заказы по России','Группы','https://t.me/+RBpfNqEkHJhlMTky'),
('ЛЕНИНГРАД"СТИМУЛ" 178~ 10%','Группы','https://t.me/+HZXHmzQ7yw5iMTU6'),
('Межгород Онлайн','Группы','https://t.me/+kns-hT3rEchlZDRi'),
('Минивэны, Ларгусы','Группы','https://t.me/+g2j9cULfGjpkNjM6'),
('Москва - Санкт-Петербург','Группы','https://t.me/+_cXEeSP-JEgxZTVi'),
('На Край Света','Группы','https://t.me/+es-PZmY8sD8yYTgy'),
('НАШ КРЫМ','Группы','https://t.me/+1A5T_SX6WwI0YzIy'),
('Победа Трансфер 🇷🇺','Группы','https://t.me/+i75Y0y21j6g1N2Fi'),
('Посылки- письма по РФ и СНГ от …','Группы','https://t.me/+muvdCF6ELmUzOWQy'),
('Регион 18','Группы','https://t.me/+z-2yHoNj5R1jNmEy'),
('СРОЧНЫЕ КГБ','Группы','https://t.me/+eetstl02-g4wYjYy'),
('Стимул Москва и ЦФО','Группы','https://t.me/+zS0Sttj5rCgwZDg6'),
('Стимул РФ (Вся Россия)','Группы','https://t.me/+_J-Mj6QlfzZkYjcy'),
('Таганрог-Ростов-РФ-Новые террит…','Группы','https://t.me/+5guwG0ZfGnVkNDli'),
('Такси по России, Крыму, Новые т…','Группы','https://t.me/+1DwaXcxOk_tjMmZi'),
('Такси Сервис','Группы','https://t.me/+YNEniqrkNd42NGEy'),
('ТРАНСФЕР-БЕЗ-ГРАНИЦ','Группы','https://t.me/+2ahjV7PV6CY1YzIy'),
('🏔KAVKAZ-TRANSFER','Группы','https://t.me/+Secxl_ncbww0NDEy'),
('👑GOLDEN V.I.P👑','Группы','https://t.me/+O_guTJWTw6NiMGQy'),
('🚖RideSnap Travel 🚖','Группы','https://t.me/+LN-dRso_IGJkOGJi'),
('Канал "МЕЖДУГОРОДНЕЕ ТАКСИ"','Группы','https://t.me/+AAAAAFlQuW11-iWPTr8L3g'),
('Драйвер МИНИВЕНЫ Саратов','Группы','https://t.me/Driver_SARATOV_MB'),
('Минивэны Челябинск Прием заказо…','Группы','https://t.me/GoldenVIPka'),
('👍Like Taxi ™👍 ( 500 р/ единораз…','Группы','https://t.me/LikeTaxi1'),
('МИНИВЕНЫ РОССИИ','Группы','https://t.me/MINIVANSROSSII'),
('Такси 💎 ОРЛАН 🚘 Межгород 💎💎💎','Группы','https://t.me/OrlanTaxi'),
('ProtectedNetwork VPN','Группы','https://t.me/ProtectedNetworkBot?start=utm_source=ref-referral=ZYbx2f4s'),
('Sevas_Group','Группы','https://t.me/Sevas_Group'),
('СВОй Трансфер','Группы','https://t.me/Svoi_transfer_rf'),
('ТАКСИ PATRIOT','Группы','https://t.me/TAXIPaTriot31'),
('🚕TAXI SERVICE РФ🇷🇺 (500р)','Группы','https://t.me/TAXl_SERVlCE_RF'),
('TM_SVOy_PUT ( 500 р единоразово…','Группы','https://t.me/TELEGA_TRANSFER_1'),
('RoadlineTaxi','Группы','https://t.me/TRANSFERFORTUNA'),
('88888888','Группы','https://t.me/Takcu_88888888'),
('VIP Z-TAXI','Группы','https://t.me/VIPTRANSFERZ'),
('👑VIP RND TRAVEL VIBES👑 (3000)','Группы','https://t.me/VIP_RNDTRAVELVIBES'),
('VipГалопомV4 (1500)','Группы','https://t.me/VipGalopomV4'),
('Z_TOUR_Z','Группы','https://t.me/Z_TOUR_Z'),
('Трансфер Межгород РФ','Группы','https://t.me/allregion_mejgorod'),
('Трансфер●РУС','Группы','https://t.me/c/1622912259/1'),
('Группа 1711671004','Группы','https://t.me/c/1711671004/1'),
('Группа 1733726514','Группы','https://t.me/c/1733726514/1'),
('Группа 1794102971','Группы','https://t.me/c/1794102971/1'),
('Группа 1839480661','Группы','https://t.me/c/1839480661/12123'),
('Самара межгород по вступлению п…','Группы','https://t.me/c/1962413147/1');